### ISSUE TITLE
Users uploaded Videos

### ISSUE THREAD

**Issue by sambudda** [muhammadbassio/YouTubeAPI3-Objective-C-wrapper#7]
How can I get a 
- URL list of all of the signed in users uploaded youtube videos? 
- Their title, description and thumbnail?

This project has no example to show that

**Comment by muhammadbassio** [comment]
You can use the below technique:
`LISTPlayListItemsForURL:(NSString *)urlStr andHandler:(void (^)(NSMutableArray *, NSError *, NSString *))handler;` where `urlStr = PlayListItemsURLforPlayList:(NSString *)playlistId withMaxResults:(NSInteger)max;` and `playlistId= channel.contentDetails.relatedPlaylists["uploads"];`
